### PR TITLE
Make use of Canonical footer

### LINKED ISSUE #1: Implement Canonical Footer
I would like to replace the footer that is present on the entirety of events.canonical.com with one more fitting and consistent with the rest of the Canonical suite of sites.

I am not sure if the best course of action is to replace the footer using templates or through jQuery, but we have both options available to us. They provide some instructions on how to use templates to replace the footer [here](https://docs.getindico.io/en/latest/config/settings/#CUSTOMIZATION_DIR) and you can see how GNOME uses jQuerry to replace the footer [here](https://gitlab.gnome.org/Teams/Engagement/Events/gnome-indico-resources/-/blob/master/js/00-main.js).

@petesfrench you had linked me to the code for the footer we should be using? Can you link that here again?

### PR DESCRIPTION
**Pull request by kewisch**
Fixes #1 

~~@petesfrench here is how to add the HTML for the footer. Do you have an easy way to condense the css styles included from the ubuntu.com stylesheet only to those classes used in the template? The current css include is changing a lot of unintended things.~~

### CODE REVIEW

**Comment by kewisch** [comment]
This contains a somewhat condensed version of the footer. The spacing isn't fully the same, mostly because Indico uses 14px font-size in :root, and Indico with the Ubuntu Summit theme applie uses 16px. @petesfrench , if you have a smart way to fix this without going through each size manually let me know. Otherwise, I think we can go with the not pixel perfect footer.

@arturo-seijas What would be a good repo to point people to for the "file a bug" link? I have the operator repo there now, but potentially this repo instead?

**Comment by kewisch** [comment]
image

**Comment by arturo-seijas** [comment]
> This contains a somewhat condensed version of the footer. The spacing isn't fully the same, mostly because Indico uses 14px font-size in :root, and Indico with the Ubuntu Summit theme applie uses 16px. @petesfrench , if you have a smart way to fix this without going through each size manually let me know. Otherwise, I think we can go with the not pixel perfect footer.
> 
> @arturo-seijas What would be a good repo to point people to for the "file a bug" link? I have the operator repo there now, but potentially this repo instead?

Where's that "file a nbug" link you are referring to?

**Comment by kewisch** [comment]
@arturo-seijas "Report a bug on this site"

**Comment by petesfrench** [comment]
@kewisch Originally the Indico theme was using 14px as the root font-size. But a request, either from Britt or you, was made to bump it up to 16px. We could revert it to 14px I believe.

**Comment by petesfrench** [comment]
You might want to experiment setting the margin-left of the footer equal to that of the `global-margin-left' value found in the theme (350px). As this will align the footer with the rest of the content.

**Comment by kewisch** [comment]
> @kewisch Originally the Indico theme was using 14px as the root font-size. But a request, either from Britt or you, was made to bump it up to 16px. We could revert it to 14px I believe.

I think having 16px is better, I believe it was Britt's request, but we have 16px on the :root element on the Ubuntu Summit theme, and 14px on the main page and non-themed conferences. If I use `rem`, the margins will change depending on if you are on the main page or the conference page. 

What we could do is bump it to 16px everywhere, but that might mess up the standard theme. Or we move the font-size change to 16px away from the root element, and then base all our rem values off of 14px. Given the conference is next week I'm inclined to keep it as is and follow up if needed. 

I didn't find `global-margin-left`, but I did find `var(--full-width)`. This stretches the footer pretty wide, so I'll keep it as is as well.

**Comment by petesfrench** [comment]
@kewisch It is important that we keep everything within the vanilla-grip pattern. This means aligning content, like we do on ubuntu:
image
There is a css variable in the theme called `--global-margin-left` for 350px. Adding this space to the left hand side of the footer should fix this.

**Pull request merged**
